apiVersion: v1
kind: PersistentVolume
metadata:
  name: model-pv
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/deep4558/Desktop/SPE_Major/Model"
